<?php

namespace AppBundle\Repository;

/**
 * HobbyScaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HobbyScaleRepository extends \Doctrine\ORM\EntityRepository
{
}
