<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * HobbyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HobbyRepository extends \Doctrine\ORM\EntityRepository
{
    
    protected $manager;
    
    public function __construct(EntityManager $manager, ClassMetadata $classMetadata)
    {
        parent::__construct($manager,$classMetadata);
        $this->manager=$manager;
    }    
    public function searchByTitle($title)
    {
        $query = $this->manager
            ->createQueryBuilder('h')
            ->select('h','hsv')
            ->from('AppBundle:Hobby', 'h')
            ->innerJoin('h.hobbyScaleValues', 'hsv')
            ->where('h.title LIKE :title')
            ->setParameter('title',"%$title%")
            ->setMaxResults(10)
            ->getQuery(); 

        $results = $query->getResult();
        return $results;   
    }
    public function getAllHobbiesWithScaleValues()
    {
       

        $query = $this->manager
            ->createQueryBuilder('h')
            ->select('h','hsv')
            ->from('AppBundle:Hobby', 'h')
            

            ->innerJoin('h.hobbyScaleValues', 'hsv')
            ->getQuery(); 

        $results = $query->getResult();
        return $results;        
        

    }
}
