<?php

namespace AppBundle\Repository;

/**
 * HobbyScaleValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HobbyScaleValueRepository extends \Doctrine\ORM\EntityRepository
{
}
