<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;
/**
 * HobbyCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HobbyCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    
    protected $manager;
    
    public function __construct(EntityManager $manager, ClassMetadata $classMetadata)
    {
        parent::__construct($manager,$classMetadata);
        $this->manager=$manager;
    }    
    
    public function getRootElements()
    {
        $query = $this->manager
            ->createQueryBuilder('c')
            ->select('c')
            ->from('AppBundle:HobbyCategory','c')
            ->where('c.parentCategory is NULL')
            ->getQuery();        
        //echo $query;    
        $results = $query->getResult();
    }
    public function getAllElements()
    {
        $query = $this->manager
            ->createQueryBuilder('c')
            ->select('c')
            ->from('AppBundle:HobbyCategory','c')
            ->getQuery();        
        //echo $query;    
        $results = $query->getResult();
        return $results;
    }
}
