<?php

namespace AppBundle\Repository;

use triguk\AuthorizationBundle\Repository\SimplePaginatorInterface;
use triguk\AuthorizationBundle\Repository\SimplePaginatorTrait;



/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements SimplePaginatorInterface
{
    use SimplePaginatorTrait;
}
