# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.formatter.hobby_tree_formatter:
        class: AppBundle\Formatter\HobbyTreeFormatter
        autowire: true

    app.formatter.hobby_scale_formatter:
        class: AppBundle\Formatter\ORMHobbyScaleFormatter

    app.twig.hobby_scale_formatter_extension:
        class: AppBundle\Twig\HobbyScaleFormatterExtension
        arguments: ['@app.formatter.hobby_scale_formatter']
                
    app.logic.hobby_logic:
        class: AppBundle\Logic\HobbyLogic
        autowire: true
        
    app.helper.hobby_scale_extractor:
        class: AppBundle\Helper\ORMHobbyScaleExtractor
        autowire: true
        
    app.helper.hobby_chooser:
        class: AppBundle\Helper\ORMHobbyChooser
        autowire: true

    app.helper.user_directory:
        class: AppBundle\Helper\FileSystemUserDirectory
        arguments: ['@security.token_storage','%kernel.root_dir%']
        autowire: true

    app.helper.hobby_scale_formatter:
        class: AppBundle\Formatter\ORMHobbyScaleFormatter

    app.hobby_scale_formatter_extension:
        class: AppBundle\Twig\HobbyScaleFormatterExtension
        arguments: ['@app.helper.hobby_scale_formatter']
        tags:
            - { name: twig.extension }

                
    app.form.type.hobby_chooser:
        class: AppBundle\Form\HobbyChooserType
        arguments: ['@doctrine.orm.entity_manager','@app.helper.hobby_scale_extractor']
        tags:
            - { name: form.type }

    app.form.type.article:
        class: AppBundle\Form\ArticleType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    app.form.type.comment:
        class: AppBundle\Form\CommentType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    app.form.type.item_delete:
        class: AppBundle\Form\ItemDeleteType
        arguments: ['@router']
        tags:
            - { name: form.type }
            
    app.tokens.elfinder_listener:
        class: AppBundle\EventListener\ElFinderListener
        arguments: ['@app.helper.user_directory']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            

